// Full country dial-code list for the phone input. Embedded (no network) so the
// picker is instant and works offline — mirrors the dial-code UX of
// afro-excellence-hub's web PhoneInput. Flag emojis are derived from the cca2
// code at runtime via regional-indicator symbols.

export type DialOption = {
  cca2: string;
  name: string;
  dial: string;
};

// [cca2, French name, dial] — every country/territory with an international
// dialing code.
const ALL: [string, string, string][] = [
  ["AF", "Afghanistan", "+93"],
  ["ZA", "Afrique du Sud", "+27"],
  ["AL", "Albanie", "+355"],
  ["DZ", "Algérie", "+213"],
  ["DE", "Allemagne", "+49"],
  ["AD", "Andorre", "+376"],
  ["AO", "Angola", "+244"],
  ["AI", "Anguilla", "+1264"],
  ["AG", "Antigua-et-Barbuda", "+1268"],
  ["SA", "Arabie saoudite", "+966"],
  ["AR", "Argentine", "+54"],
  ["AM", "Arménie", "+374"],
  ["AW", "Aruba", "+297"],
  ["AU", "Australie", "+61"],
  ["AT", "Autriche", "+43"],
  ["AZ", "Azerbaïdjan", "+994"],
  ["BS", "Bahamas", "+1242"],
  ["BH", "Bahreïn", "+973"],
  ["BD", "Bangladesh", "+880"],
  ["BB", "Barbade", "+1246"],
  ["BE", "Belgique", "+32"],
  ["BZ", "Belize", "+501"],
  ["BJ", "Bénin", "+229"],
  ["BM", "Bermudes", "+1441"],
  ["BT", "Bhoutan", "+975"],
  ["BY", "Biélorussie", "+375"],
  ["BO", "Bolivie", "+591"],
  ["BA", "Bosnie-Herzégovine", "+387"],
  ["BW", "Botswana", "+267"],
  ["BR", "Brésil", "+55"],
  ["BN", "Brunei", "+673"],
  ["BG", "Bulgarie", "+359"],
  ["BF", "Burkina Faso", "+226"],
  ["BI", "Burundi", "+257"],
  ["KH", "Cambodge", "+855"],
  ["CM", "Cameroun", "+237"],
  ["CA", "Canada", "+1"],
  ["CV", "Cap-Vert", "+238"],
  ["BQ", "Pays-Bas caribéens", "+599"],
  ["KY", "Îles Caïmans", "+1345"],
  ["CL", "Chili", "+56"],
  ["CN", "Chine", "+86"],
  ["CY", "Chypre", "+357"],
  ["CO", "Colombie", "+57"],
  ["KM", "Comores", "+269"],
  ["CG", "Congo", "+242"],
  ["CD", "RD Congo", "+243"],
  ["CK", "Îles Cook", "+682"],
  ["KR", "Corée du Sud", "+82"],
  ["KP", "Corée du Nord", "+850"],
  ["CR", "Costa Rica", "+506"],
  ["CI", "Côte d'Ivoire", "+225"],
  ["HR", "Croatie", "+385"],
  ["CU", "Cuba", "+53"],
  ["CW", "Curaçao", "+599"],
  ["DK", "Danemark", "+45"],
  ["DJ", "Djibouti", "+253"],
  ["DM", "Dominique", "+1767"],
  ["EG", "Égypte", "+20"],
  ["AE", "Émirats arabes unis", "+971"],
  ["EC", "Équateur", "+593"],
  ["ER", "Érythrée", "+291"],
  ["ES", "Espagne", "+34"],
  ["EE", "Estonie", "+372"],
  ["SZ", "Eswatini", "+268"],
  ["US", "États-Unis", "+1"],
  ["ET", "Éthiopie", "+251"],
  ["FK", "Îles Malouines", "+500"],
  ["FO", "Îles Féroé", "+298"],
  ["FJ", "Fidji", "+679"],
  ["FI", "Finlande", "+358"],
  ["FR", "France", "+33"],
  ["GA", "Gabon", "+241"],
  ["GM", "Gambie", "+220"],
  ["GE", "Géorgie", "+995"],
  ["GH", "Ghana", "+233"],
  ["GI", "Gibraltar", "+350"],
  ["GR", "Grèce", "+30"],
  ["GD", "Grenade", "+1473"],
  ["GL", "Groenland", "+299"],
  ["GP", "Guadeloupe", "+590"],
  ["GU", "Guam", "+1671"],
  ["GT", "Guatemala", "+502"],
  ["GG", "Guernesey", "+44"],
  ["GN", "Guinée", "+224"],
  ["GW", "Guinée-Bissau", "+245"],
  ["GQ", "Guinée équatoriale", "+240"],
  ["GY", "Guyana", "+592"],
  ["GF", "Guyane française", "+594"],
  ["HT", "Haïti", "+509"],
  ["HN", "Honduras", "+504"],
  ["HK", "Hong Kong", "+852"],
  ["HU", "Hongrie", "+36"],
  ["IM", "Île de Man", "+44"],
  ["IN", "Inde", "+91"],
  ["ID", "Indonésie", "+62"],
  ["IQ", "Irak", "+964"],
  ["IR", "Iran", "+98"],
  ["IE", "Irlande", "+353"],
  ["IS", "Islande", "+354"],
  ["IL", "Israël", "+972"],
  ["IT", "Italie", "+39"],
  ["JM", "Jamaïque", "+1876"],
  ["JP", "Japon", "+81"],
  ["JE", "Jersey", "+44"],
  ["JO", "Jordanie", "+962"],
  ["KZ", "Kazakhstan", "+7"],
  ["KE", "Kenya", "+254"],
  ["KG", "Kirghizistan", "+996"],
  ["KI", "Kiribati", "+686"],
  ["KW", "Koweït", "+965"],
  ["LA", "Laos", "+856"],
  ["LS", "Lesotho", "+266"],
  ["LV", "Lettonie", "+371"],
  ["LB", "Liban", "+961"],
  ["LR", "Liberia", "+231"],
  ["LY", "Libye", "+218"],
  ["LI", "Liechtenstein", "+423"],
  ["LT", "Lituanie", "+370"],
  ["LU", "Luxembourg", "+352"],
  ["MO", "Macao", "+853"],
  ["MK", "Macédoine du Nord", "+389"],
  ["MG", "Madagascar", "+261"],
  ["MY", "Malaisie", "+60"],
  ["MW", "Malawi", "+265"],
  ["MV", "Maldives", "+960"],
  ["ML", "Mali", "+223"],
  ["MT", "Malte", "+356"],
  ["MP", "Îles Mariannes du Nord", "+1670"],
  ["MA", "Maroc", "+212"],
  ["MH", "Îles Marshall", "+692"],
  ["MQ", "Martinique", "+596"],
  ["MU", "Maurice", "+230"],
  ["MR", "Mauritanie", "+222"],
  ["YT", "Mayotte", "+262"],
  ["MX", "Mexique", "+52"],
  ["FM", "Micronésie", "+691"],
  ["MD", "Moldavie", "+373"],
  ["MC", "Monaco", "+377"],
  ["MN", "Mongolie", "+976"],
  ["ME", "Monténégro", "+382"],
  ["MS", "Montserrat", "+1664"],
  ["MZ", "Mozambique", "+258"],
  ["MM", "Myanmar", "+95"],
  ["NA", "Namibie", "+264"],
  ["NR", "Nauru", "+674"],
  ["NP", "Népal", "+977"],
  ["NI", "Nicaragua", "+505"],
  ["NE", "Niger", "+227"],
  ["NG", "Nigéria", "+234"],
  ["NU", "Niue", "+683"],
  ["NO", "Norvège", "+47"],
  ["NC", "Nouvelle-Calédonie", "+687"],
  ["NZ", "Nouvelle-Zélande", "+64"],
  ["OM", "Oman", "+968"],
  ["UG", "Ouganda", "+256"],
  ["UZ", "Ouzbékistan", "+998"],
  ["PK", "Pakistan", "+92"],
  ["PW", "Palaos", "+680"],
  ["PS", "Palestine", "+970"],
  ["PA", "Panama", "+507"],
  ["PG", "Papouasie-Nouvelle-Guinée", "+675"],
  ["PY", "Paraguay", "+595"],
  ["NL", "Pays-Bas", "+31"],
  ["PE", "Pérou", "+51"],
  ["PH", "Philippines", "+63"],
  ["PL", "Pologne", "+48"],
  ["PF", "Polynésie française", "+689"],
  ["PR", "Porto Rico", "+1787"],
  ["PT", "Portugal", "+351"],
  ["QA", "Qatar", "+974"],
  ["RE", "La Réunion", "+262"],
  ["RO", "Roumanie", "+40"],
  ["GB", "Royaume-Uni", "+44"],
  ["RU", "Russie", "+7"],
  ["RW", "Rwanda", "+250"],
  ["BL", "Saint-Barthélemy", "+590"],
  ["KN", "Saint-Kitts-et-Nevis", "+1869"],
  ["SM", "Saint-Marin", "+378"],
  ["MF", "Saint-Martin", "+590"],
  ["SX", "Sint Maarten", "+1721"],
  ["VC", "Saint-Vincent-et-les-Grenadines", "+1784"],
  ["LC", "Sainte-Lucie", "+1758"],
  ["SB", "Îles Salomon", "+677"],
  ["SV", "Salvador", "+503"],
  ["WS", "Samoa", "+685"],
  ["AS", "Samoa américaines", "+1684"],
  ["ST", "Sao Tomé-et-Principe", "+239"],
  ["SN", "Sénégal", "+221"],
  ["RS", "Serbie", "+381"],
  ["SC", "Seychelles", "+248"],
  ["SL", "Sierra Leone", "+232"],
  ["SG", "Singapour", "+65"],
  ["SK", "Slovaquie", "+421"],
  ["SI", "Slovénie", "+386"],
  ["SO", "Somalie", "+252"],
  ["SD", "Soudan", "+249"],
  ["SS", "Soudan du Sud", "+211"],
  ["LK", "Sri Lanka", "+94"],
  ["SE", "Suède", "+46"],
  ["CH", "Suisse", "+41"],
  ["SR", "Suriname", "+597"],
  ["SY", "Syrie", "+963"],
  ["TJ", "Tadjikistan", "+992"],
  ["TW", "Taïwan", "+886"],
  ["TZ", "Tanzanie", "+255"],
  ["TD", "Tchad", "+235"],
  ["CZ", "Tchéquie", "+420"],
  ["TH", "Thaïlande", "+66"],
  ["TL", "Timor oriental", "+670"],
  ["TG", "Togo", "+228"],
  ["TK", "Tokelau", "+690"],
  ["TO", "Tonga", "+676"],
  ["TT", "Trinité-et-Tobago", "+1868"],
  ["TN", "Tunisie", "+216"],
  ["TM", "Turkménistan", "+993"],
  ["TR", "Turquie", "+90"],
  ["TC", "Îles Turques-et-Caïques", "+1649"],
  ["TV", "Tuvalu", "+688"],
  ["UA", "Ukraine", "+380"],
  ["UY", "Uruguay", "+598"],
  ["VU", "Vanuatu", "+678"],
  ["VA", "Vatican", "+379"],
  ["VE", "Venezuela", "+58"],
  ["VG", "Îles Vierges britanniques", "+1284"],
  ["VI", "Îles Vierges américaines", "+1340"],
  ["VN", "Vietnam", "+84"],
  ["YE", "Yémen", "+967"],
  ["ZM", "Zambie", "+260"],
  ["ZW", "Zimbabwe", "+263"],
];

// Countries pinned to the top of the picker (most relevant to PEEA members),
// in display order. Everything else follows, sorted alphabetically.
const PRIORITY = [
  "FR", "BE", "CH", "LU", "CA", "US", "GB", "DE", "ES", "IT", "PT", "NL",
  "CI", "SN", "CM", "ML", "BF", "BJ", "TG", "NE", "GN", "GA", "CG", "CD",
  "TD", "MR", "MG", "MA", "DZ", "TN",
];

export function flagOf(cca2: string): string {
  return cca2
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(127397 + c.charCodeAt(0)));
}

const byCca2 = new Map(ALL.map(([cca2, name, dial]) => [cca2, { cca2, name, dial }]));

const priorityOptions: DialOption[] = PRIORITY.map((c) => byCca2.get(c)!).filter(Boolean);

const restOptions: DialOption[] = ALL.map(([cca2, name, dial]) => ({ cca2, name, dial }))
  .filter((o) => !PRIORITY.includes(o.cca2))
  .sort((a, b) => a.name.localeCompare(b.name, "fr"));

export const DIAL_OPTIONS: DialOption[] = [...priorityOptions, ...restOptions];

export const DEFAULT_CCA2 = "FR"; // France (+33)

export function optionByCca2(cca2: string): DialOption {
  return byCca2.get(cca2) ?? byCca2.get(DEFAULT_CCA2)!;
}

// Longest-prefix match so a stored E.164 number can be split back into a country
// + national part when pre-filling the input.
export function parseE164(value: string): { cca2: string; national: string } | null {
  if (!value?.startsWith("+")) return null;
  let best: DialOption | null = null;
  for (const o of DIAL_OPTIONS) {
    if (value.startsWith(o.dial) && (!best || o.dial.length > best.dial.length)) {
      best = o;
    }
  }
  if (!best) return null;
  return { cca2: best.cca2, national: value.slice(best.dial.length) };
}
